id: PFF2B4F06
initial_creation_type: input
source_metadata:
  title: Preliminary Practices & Commentaries
  language: bo
  description: 'A series of texts, including commentaries, related to the preliminary
    practices, or ngöndro (sngon ''gro), from various cycles:'
  volume:
    12a616f4a4da42c6807048dcfdb7072f:
      title: The Recitation for the Gradual Path of the Preliminaries from The Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī
      parent: General
    6408c1467b44406ba079c9c10d60f5e8:
      title: 'Illuminating the Path to Liberation: A Preliminary Practice (Ngöndro)'
      parent: General
    c2ef956857004f0985d227e352d43ec1:
      title: Signs that the Common Preliminary Practices Have Penetrated the Mind
      parent: General
    0283019fc04b446cb2e6479c9c0243f0:
      title: Concise Preliminaries Practice
      parent: General
    d2ced1bc51ec41e9a4effe65c4924e66:
      title: Advice to Damngak Gyatso of Do
      parent: General
    69f0aa8583224e78806c2f1c9b7f378c:
      title: 'A Torch for the Path to Omniscience: A Word by Word Commentary to the
        Longchen Nyingtik Ngöndro'
      parent: Longchen Nyingtik Ngöndro
    c953a5e889b0441ba8a6e7ec97941ef1:
      title: 'The Excellent Path to Omniscience: The Dzogchen Preliminary Practice
        of Longchen Nyingtik'
      parent: Longchen Nyingtik Ngöndro
    95125d58bf024a21ab61e0910aa7ae1a:
      title: 'A Profound Concentration of Nectar: Essentialized Stages of Visualization
        for the Preliminary Practices of the Heart Essence of the Vast Expanse (Longchen
        Nyingtik)'
      parent: Longchen Nyingtik Ngöndro
    c98cf152ad36434ea304e9661be80bb4:
      title: 'Illuminating the Excellent Path to Omniscience: Notes on the Longchen
        Nyingtik Ngöndro'
      parent: Longchen Nyingtik Ngöndro
    c95a17c8f00446aa83650cb4c9e96fc1:
      title: Brief Guide to the Stages of Visualization for the Ngöndro Practice
      parent: Longchen Nyingtik Ngöndro
    520b134a323e408a8a417830fe8d96a7:
      title: Ngöndro Compendium—Part 1—Invoking the Lama
      parent: Ngöndro Compendium
    990caa620c8d4139a1110a23303fc165:
      title: Ngöndro Compendium—Part 2—Taking Refuge
      parent: Ngöndro Compendium
    102811f0ecc140b9b0dc386795b9bc16:
      title: Ngöndro Compendium—Part 3—Arousing Bodhichitta
      parent: Ngöndro Compendium
    78286f9fb707417094726f3c01aabb04:
      title: Ngöndro Compendium—Part 4—Mandala Offering
      parent: Ngöndro Compendium
    afc3885f72374e63baad8da8a6cf96f0:
      title: 'The Excellent Path to Enlightenment: A Brief Practice of the Preliminaries'
      parent: Ngöndro by Jamyang Khyentse Wangpo
    e273adf729cd455c81ef75fb20c5a89f:
      title: A Concise Recitation of the Preliminary Practice according to the New
        Treasure of Dudjom
      parent: Dudjom Tersar Ngöndro
    1f4546b7039d4be3a08777f6ac1f7642:
      title: Brief Notes on the Visualization for the Concise Recitation of the Pure
        Vision Preliminary Practice
      parent: Dudjom Tersar Ngöndro
    fafeb1dd96b345679538236578a73f92:
      title: Guru Yoga
      parent: Guru Yoga
    b6f58f9aa9ff4b38bee9e7f5b4320376:
      title: The Concise Mahāmudrā Preliminaries Arranged for Recitation
      parent: Mahāmudrā
created_at: '2022-03-01T04:49:32.930985'
last_modified_at: '2022-03-01T04:49:32.930987'
statistics:
  total_words: 52598
  total_non_words: 5167
quality:
  non_words_ratio: 0.1
